### ISSUE TITLE
EDI or mEDI?

### ISSUE THREAD

**Issue by eugenelyj** [panpanfei/Bringing-a-Blurry-Frame-Alive-at-High-Frame-Rate-with-an-Event-Camera#2]
Thanks for you work!! I am not sure that Is the code for EDI or mEDI?

**Comment by panpanfei** [comment]
Hi, the code is for EDI, mEDI will be released after publishing. Thanks for your interests.

**Comment by YingjianYu** [comment]
Hello, Has the mEDI  been released？
