### ISSUE TITLE
meaning of timestamp t_0

### ISSUE THREAD

**Issue by c13proto** [panpanfei/Bringing-a-Blurry-Frame-Alive-at-High-Frame-Rate-with-an-Event-Camera#3]
Thank you for sharing interesting work, I am trying to reproduce your work by myself.
But I am struggling to understand the timestamp relation written in your paper clearly.
Particularly, it is hard to understand t_0 which is used for calculating event model. 
How do you decide the parameter t_0 ?
And,  please tell me the relation between t, t_ref, t_0.

**Comment by panpanfei** [comment]
Hi,
The delta function equals to 1 if t=t_0 and zero otherwise.
If you already have the event data, you do not need to decide t, t_ref, and t_0.
You can assume t_ref is the current timestamp, t is the timestamp you want to reach.
We also upload our slide and may do some help.
Cheers,
Pan

**Comment by c13proto** [comment]
ok, I am looking forward to new slide.
And I hope you to share high framerate dataset.
thank you!

**Comment by panpanfei** [comment]
Hi, the slide has been uploaded before, as well as the real event dataset.
