### ISSUE TITLE
Questions on eq(3)

### ISSUE THREAD

**Issue by shyu4184** [panpanfei/Bringing-a-Blurry-Frame-Alive-at-High-Frame-Rate-with-an-Event-Camera#4]
Thank you for sharing your work. 
I'm studying your cvpr paper and I have two questions on eq. (3). 
I understood that the first integral gives the events occurred in the latent images and the second integral gives the latent frame. 

In eq. (3), the exponential function was just used to convert the multiplication problem to an addition problem by taking the logarithmic transformation on both sides in eq. (4)? is it right? 
Besides, I don't exactly understand why `E(t)` is multiplied by threshold `c`. Is threshold `c` was used to penalize the blurring in the edge region of the input frame? 

I watched the presentation in CVPR 2019, but I'm not sure I'm correctly understanding your paper. 
Could you explain how eq. (3) derived from the previous equations?  

Thank you!

**Comment by panpanfei** [comment]
Hi, 

Thanks for your interests.

Yes, the transfer from eq. 3 to e1. 4 just aims to convert the multiplication to addition.

For threshold c, maybe we can go back to eq. 1. 
An event can only be recorded when |log(L(x,t1)/L(x,t2))|>c. 
t1 and t2 are the timestamps for two consecutive events respectively. 

The output of an event is -1 or 1, not the absolute intensity. 
So we assume log(L(x,t1)/L(x,t2)) \approx (\sigma c).

Cheers,
Pan
