### ISSUE TITLE
how did you get the time shift in your code?

### ISSUE THREAD

**Issue by yuanhaowang1213** [panpanfei/Bringing-a-Blurry-Frame-Alive-at-High-Frame-Rate-with-an-Event-Camera#5]
There is a parameter t_shift, how did you find this value? And in you model the blur is caused by the events before and after this image?

**Comment by panpanfei** [comment]
The time shift is from signal jitter and hystereisis of the event camera， we get this parameter experimentally. 
Yes, but not the events, because of the latent image (non-exist) before and after image during the exposure time.
