### ISSUE TITLE
Why there is no trace of f(i.e. the timestamp of the blurry image) in the code?

### ISSUE THREAD

**Issue by LavieC** [panpanfei/Bringing-a-Blurry-Frame-Alive-at-High-Frame-Rate-with-an-Event-Camera#6]
Hi Pan,

I have been try to reproduce your amazing work, yet there is a problem bothering me. 
![image](https://user-images.githubusercontent.com/22268423/64316136-86a68b00-cfe6-11e9-89ce-55922dcdee02.png)

As in your equation 5 & 6, the lower limit of the integral f(time stamp of blurry image) is supposed to be critical in calculation, however in your functions "warpingBlur2If" and "event2video_final" there is no input concerning f. 
So how do you calculate the integral of events without the value of f?

**Comment by panpanfei** [comment]
The input needs the exposure starting and ending point 'eventstart', 'eventend'. We defined the f as abs(eventstart-eventend)/2.

**Comment by LavieC** [comment]
Thanks~
