### ISSUE TITLE
How much time needed to process one image?

### ISSUE THREAD

**Issue by luodanping** [panpanfei/Bringing-a-Blurry-Frame-Alive-at-High-Frame-Rate-with-an-Event-Camera#7]
Hello,
        Thanks for sharing your great work at first.
        After reading your paper, I am interested in the performance of your code. You said in your paper "The framework is implemented by using Matlab with C++ wrapper" and it takes around 1.5s for one image. So the core algorithm of EDI is coded by C++? Can performance be imporced by pure C++?

**Comment by panpanfei** [comment]
Hi, time performance can be improved by pire C++.
