### ISSUE TITLE
Error in event2video_final

### ISSUE THREAD

**Issue by AmoghTiwari** [panpanfei/Bringing-a-Blurry-Frame-Alive-at-High-Frame-Rate-with-an-Event-Camera#8]
Hi, thanks for your work.

While trying to run your code, I am getting the following error message:
![Screenshot from 2021-02-20 11-29-57](https://user-images.githubusercontent.com/40275901/108585877-df9be780-7370-11eb-8721-6001f4e76a53.png)

Details of the variables are as follows:
blur: 180x240 double
x: 130x1 double
y:130x1 double
pol:130x1 double
t: 130x1 double
eventstart: 83.2369
eventend: 83.2960
exptime: 0.0591
v_length: 100

Here's a snippet of my code:
![Screenshot from 2021-02-20 11-46-45](https://user-images.githubusercontent.com/40275901/108585939-5df88980-7371-11eb-94d9-7a46db58ce4a.png)

From what I understand, the error is coming in the event2video_final() function call. However, since the source code of event2video_final is not available (only the .p file is available), I am unable to proceed further. It would be great if you could suggest what might be causing this error and how it can be fixed.

Thanks in Advanced.

**Comment by panpanfei** [comment]
Hi, I suppose the error might because of your short testing event stream. Would you mind trying a more dense event stream?

**Comment by chensong1995** [comment]
I encountered the same issue. It turns out that the data I use have some invalid events. I was able to fix the problem by changing [this line](https://github.com/panpanfei/Bringing-a-Blurry-Frame-Alive-at-High-Frame-Rate-with-an-Event-Camera/blob/master/event_cvpr_github/main_video2.m#L41) to
```
idx = (t>=eventstart)&(t<=eventend)&(x>=0)&(y>=0);
```
